name: "Build & Release"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            build_cmd: flutter build macos --release
            artifact_path: build/macos/Build/Products/Release
            artifact_name: sitstand-mac.zip
          - os: windows-latest
            build_cmd: flutter build windows --release
            artifact_path: build/windows/x64/runner/Release
            artifact_name: sitstand-win.zip
          - os: ubuntu-latest
            build_cmd: |
              sudo apt-get update -y
              sudo apt-get install -y libgtk-3-dev cmake ninja-build libblkid-dev liblzma-dev libayatana-appindicator3-dev
              flutter build linux --release

              # Prepare sitstand.AppDir
              mkdir -p sitstand.AppDir/usr/bin

              cp -r build/linux/x64/release/bundle/sitstand sitstand.AppDir/usr/bin
              chmod +x sitstand.AppDir/usr/bin/sitstand
              cp assets/icon.png sitstand.AppDir/sitstand.png

              cat > sitstand.AppDir/AppRun <<EOF
              #!/bin/bash
              HERE="$(dirname "$(readlink -f "${0}")")"
              exec "$HERE/usr/bin/sitstand" "$@"
              EOF

              chmod +x sitstand.AppDir/AppRun

              cat > sitstand.AppDir/sitstand.desktop <<EOF
              [Desktop Entry]
              Type=Application
              Name=SitStand
              Exec=sitstand
              Icon=sitstand
              Categories=Utility;
              EOF
              
              wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
              chmod +x appimagetool-x86_64.AppImage
              ./appimagetool-x86_64.AppImage sitstand.AppDir sitstand-linux.AppImage
            artifact_path: build/linux/x64/release/bundle
            artifact_name: sitstand-linux.AppImage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Inno Setup
        if: matrix.os == 'windows-latest'
        run: choco install innosetup

      - name: Build for ${{ matrix.os }}
        run: ${{ matrix.build_cmd }}

      - name: Create Windows Installer
        if: matrix.os == 'windows-latest'
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: pwsh

      - name: List files after installer build
        if: matrix.os == 'windows-latest'
        run: dir -Recurse
        shell: pwsh

      - name: Upload Windows installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: sitstand-setup.exe
          path: Output/sitstand-setup.exe

      - name: Package artifact on Windows
        if: matrix.os == 'windows-latest'
        run: |
          $files = Get-ChildItem -Path build/windows/x64/runner/Release -Recurse | ForEach-Object { $_.FullName }
          Compress-Archive -Path $files -DestinationPath ${{ matrix.artifact_name }}
        shell: pwsh

      - name: Package artifact on Linux/macOS
        if: matrix.os == 'macos-latest'
        run: zip -r ${{ matrix.artifact_name }} ${{ matrix.artifact_path }}
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

      - name: Extract version from pubspec.yaml
        id: extract_version
        if: matrix.os != 'windows-latest'
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Extract version from pubspec.yaml for Windows
        id: extract_version_win
        if: matrix.os == 'windows-latest'
        run: |
          $version = (Select-String -Path pubspec.yaml -Pattern '^version: ' | ForEach-Object {
            ($_ -split '\s+')[1].Trim()
          })
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding ascii -Append
        shell: pwsh

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download Mac artifact
        uses: actions/download-artifact@v4
        with:
          name: sitstand-mac.zip

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: sitstand-win.zip

      - name: Download Windows setup artifact
        uses: actions/download-artifact@v4
        with:
          name: sitstand-setup.exe

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: sitstand-linux.AppImage

      - name: Extract version from pubspec.yaml for Linux/MacOS
        id: extract_version
        if: matrix.os != 'windows-latest'
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: bash

      - name: Extract version from pubspec.yaml for Windows
        id: extract_version_win
        if: matrix.os == 'windows-latest'
        run: |
          $version = (Select-String -Path pubspec.yaml -Pattern '^version: ' | ForEach-Object {
            ($_ -split '\s+')[1].Trim()
          })
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding ascii -Append
        shell: pwsh

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Modify Tag if exists
        if: env.TAG_EXISTS == 'true'
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
          artifacts: |
            sitstand-mac.zip
            sitstand-win.zip
            sitstand-setup.exe
            sitstand-linux.AppImage
          allowUpdates: true
